### PR TITLE
Attachments! [Take 2]

### LINKED ISSUE #714: Add attachments
### Description

The XCTest framework has an attachment feature, which is beneficial for snapshot tests to visualize the differences. It would be advantageous if this feature were incorporated into SwiftTesting as well.

### PR DESCRIPTION
**Pull request by grynspan**
This PR introduces a new experimental feature, attachments. With this feature, you can "attach" values that conform to a new `Test.Attachable` protocol to a test. With the right command-line incantation (TBD), Swift Testing will automatically write attachments to disk for you.

> [!NOTE]
> This PR does not teach Xcode or VS Code how to handle attachments produced by
> Swift Testing, nor does it add the necessary command-line arguments to the
> `swift test` command-line tool.

This PR is one of a series that I'll be posting to build out this feature.

As always, keep in mind that symbols marked `@_spi(Experimental)` are subject to change or removal without notice.

Resolves #714.
Resolves rdar://88648735.

### Checklist:

- [x] Code and documentation should follow the style of the [Style Guide](https://github.com/apple/swift-testing/blob/main/Documentation/StyleGuide.md).
- [x] If public symbols are renamed or modified, DocC references should be updated.

### CODE REVIEW

**Comment by grynspan** [comment]
@swift-ci test

**Comment by grynspan** [comment]
@swift-ci test

**Comment by grynspan** [comment]
@swift-ci test Windows

**Comment by grynspan** [comment]
@swift-ci test Windows

**Comment by grynspan** [comment]
@swift-ci test

**Comment by grynspan** [comment]
@swift-ci test Windows

**Comment by grynspan** [comment]
@swift-ci test Windows

**Comment by grynspan** [comment]
@swift-ci test

**Comment by grynspan** [comment]
@swift-ci test Windows

**Comment by grynspan** [comment]
@swift-ci test Windows

**Comment by grynspan** [comment]
@swift-ci test Windows

**Comment by grynspan** [comment]
@swift-ci test

**Comment by grynspan** [comment]
@swift-ci test

**Comment by grynspan** [comment]
@swift-ci test Windows

**Comment by grynspan** [comment]
@swift-ci test Windows

**Comment by grynspan** [comment]
@swift-ci test Windows

**Comment by grynspan** [comment]
@swift-ci test Windows

**Comment by grynspan** [comment]
@swift-ci test Windows

**Comment by grynspan** [comment]
@swift-ci test Windows

**Comment by grynspan** [comment]
@swift-ci test

**Comment by grynspan** [comment]
@swift-ci test Windows

**Comment by grynspan** [comment]
@swift-ci test Windows

**Comment by grynspan** [comment]
@swift-ci test Windows

**Comment by grynspan** [comment]
@swift-ci test Windows

**Comment by grynspan** [comment]
@swift-ci test

**Comment by grynspan** [comment]
@swift-ci test Linux

**Comment by grynspan** [comment]
@swift-ci test macOS

**Review by briancroom — APPROVED** [review]

**Comment by grynspan** [comment]
Reapplies #770 after it was reverted in #793.

**Pull request merged**
